# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PCIe.xdc

# XDC: new/debug_leds.xdc

# Block Designs: bd/PCIe/PCIe.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe || ORIG_REF_NAME==PCIe} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_axi_interconnect_0_imp_xbar_0/PCIe_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_axi_interconnect_0_1/PCIe_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_1 || ORIG_REF_NAME==PCIe_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_clk_wiz_0_0 || ORIG_REF_NAME==PCIe_clk_wiz_0_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_rst_mig_7series_0_100M_0/PCIe_rst_mig_7series_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==PCIe_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_util_ds_buf_0_0/PCIe_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_util_ds_buf_0_0 || ORIG_REF_NAME==PCIe_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_xdma_0_1/PCIe_xdma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_xdma_0_1 || ORIG_REF_NAME==PCIe_xdma_0_1} -quiet] -quiet

# IP: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_4/pcie2_fifo_generator_tgt_brdg.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie2_fifo_generator_tgt_brdg || ORIG_REF_NAME==pcie2_fifo_generator_tgt_brdg} -quiet] -quiet

# IP: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_3/pcie2_fifo_generator_dma_cpl.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie2_fifo_generator_dma_cpl || ORIG_REF_NAME==pcie2_fifo_generator_dma_cpl} -quiet] -quiet

# IP: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_2/xdma_v4_2_2_blk_mem_64_noreg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_2_2_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_2_2_blk_mem_64_noreg_be} -quiet] -quiet

# IP: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_1/xdma_v4_2_2_blk_mem_64_reg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_2_2_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_2_2_blk_mem_64_reg_be} -quiet] -quiet

# IP: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_0/PCIe_xdma_0_1_pcie2_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_xdma_0_1_pcie2_ip || ORIG_REF_NAME==PCIe_xdma_0_1_pcie2_ip} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_mig_7series_0_1/PCIe_mig_7series_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_mig_7series_0_1 || ORIG_REF_NAME==PCIe_mig_7series_0_1} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_axi_dma_0_0/PCIe_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_axi_dma_0_0 || ORIG_REF_NAME==PCIe_axi_dma_0_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_fpga_relu_accelerator_0_0/PCIe_fpga_relu_accelerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_fpga_relu_accelerator_0_0 || ORIG_REF_NAME==PCIe_fpga_relu_accelerator_0_0} -quiet] -quiet

# IP: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_fpga_relu_accelerator_0_0/hdl/ip/fpga_relu_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1_ip/fpga_relu_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_relu_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1_ip || ORIG_REF_NAME==fpga_relu_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1_ip} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_0/PCIe_axi_interconnect_0_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_us_0 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_us_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_1/PCIe_axi_interconnect_0_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_us_1 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_us_1} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_2/PCIe_axi_interconnect_0_imp_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_us_2 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_us_2} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_cc_0/PCIe_axi_interconnect_0_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_cc_0 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_cc_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_ds_0/PCIe_axi_interconnect_0_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_ds_0 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_ds_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_pc_0/PCIe_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_ds_1/PCIe_axi_interconnect_0_imp_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_ds_1 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_ds_1} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_pc_1/PCIe_axi_interconnect_0_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_pc_1 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_pc_1} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_build_version_led_0_0/PCIe_build_version_led_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_build_version_led_0_0 || ORIG_REF_NAME==PCIe_build_version_led_0_0} -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_clk_wiz_0_0 || ORIG_REF_NAME==PCIe_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_clk_wiz_0_0 || ORIG_REF_NAME==PCIe_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_rst_mig_7series_0_100M_0/PCIe_rst_mig_7series_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==PCIe_rst_mig_7series_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_util_ds_buf_0_0/PCIe_util_ds_buf_0_0_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_util_ds_buf_0_0/PCIe_util_ds_buf_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_util_ds_buf_0_0 || ORIG_REF_NAME==PCIe_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_4/pcie2_fifo_generator_tgt_brdg.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie2_fifo_generator_tgt_brdg || ORIG_REF_NAME==pcie2_fifo_generator_tgt_brdg} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_3/pcie2_fifo_generator_dma_cpl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie2_fifo_generator_dma_cpl || ORIG_REF_NAME==pcie2_fifo_generator_dma_cpl} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_2/xdma_v4_2_2_blk_mem_64_noreg_be_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_1/xdma_v4_2_2_blk_mem_64_reg_be_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip-PCIE_X0Y0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_xdma_0_1_pcie2_ip || ORIG_REF_NAME==PCIe_xdma_0_1_pcie2_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/ip_xilinx_pcie_2_1_7x_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_xdma_0_1_pcie2_ip || ORIG_REF_NAME==PCIe_xdma_0_1_pcie2_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_0/synth/PCIe_xdma_0_1_pcie2_ip_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/PCIe_xdma_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_xdma_0_1 || ORIG_REF_NAME==PCIe_xdma_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/source/PCIe_xdma_0_1_pcie3_7vx_ip.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_xdma_0_1 || ORIG_REF_NAME==PCIe_xdma_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/synth/PCIe_xdma_0_1_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_mig_7series_0_1/PCIe_mig_7series_0_1/user_design/constraints/PCIe_mig_7series_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCIe_mig_7series_0_1 || ORIG_REF_NAME==PCIe_mig_7series_0_1} -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_mig_7series_0_1/PCIe_mig_7series_0_1/user_design/constraints/PCIe_mig_7series_0_1_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_dma_0_0/PCIe_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_axi_dma_0_0 || ORIG_REF_NAME==PCIe_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_dma_0_0/PCIe_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_axi_dma_0_0 || ORIG_REF_NAME==PCIe_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_fpga_relu_accelerator_0_0/constraints/fpga_relu_accelerator_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_0/PCIe_axi_interconnect_0_imp_auto_us_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_us_0 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_0/PCIe_axi_interconnect_0_imp_auto_us_0_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_1/PCIe_axi_interconnect_0_imp_auto_us_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_us_1 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_1/PCIe_axi_interconnect_0_imp_auto_us_1_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_2/PCIe_axi_interconnect_0_imp_auto_us_2_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_us_2 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_us_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_2/PCIe_axi_interconnect_0_imp_auto_us_2_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_cc_0/PCIe_axi_interconnect_0_imp_auto_cc_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_cc_0 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_cc_0/PCIe_axi_interconnect_0_imp_auto_cc_0_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_ds_0/PCIe_axi_interconnect_0_imp_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_ds_0 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_ds_0/PCIe_axi_interconnect_0_imp_auto_ds_0_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_pc_0/PCIe_axi_interconnect_0_imp_auto_pc_0_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_ds_1/PCIe_axi_interconnect_0_imp_auto_ds_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_imp_auto_ds_1 || ORIG_REF_NAME==PCIe_axi_interconnect_0_imp_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_ds_1/PCIe_axi_interconnect_0_imp_auto_ds_1_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_pc_1/PCIe_axi_interconnect_0_imp_auto_pc_1_ooc.xdc

# XDC: /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/PCIe_ooc.xdc
