# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.runs/synth_1/PCIe_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 3
set_param general.usePosixSpawnForFork 1
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.cache/wt [current_project]
set_property parent.project_path /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/wroomhers/Desktop/vitis_workspace/relu_accelerator [current_project]
update_ip_catalog
set_property ip_output_repo /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.srcs/sources_1/new/build_version_led.v
  /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/hdl/PCIe_wrapper.v
}
add_files /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.srcs/sources_1/bd/PCIe/PCIe.bd
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_rst_mig_7series_0_100M_0/PCIe_rst_mig_7series_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_util_ds_buf_0_0/PCIe_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_util_ds_buf_0_0/PCIe_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_4/pcie2_fifo_generator_tgt_brdg.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_3/pcie2_fifo_generator_dma_cpl.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_2/xdma_v4_2_2_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_1/xdma_v4_2_2_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/ip_xilinx_pcie_2_1_7x_late.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_0/synth/PCIe_xdma_0_1_pcie2_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/PCIe_xdma_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/source/PCIe_xdma_0_1_pcie3_7vx_ip.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/synth/PCIe_xdma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_mig_7series_0_1/PCIe_mig_7series_0_1/user_design/constraints/PCIe_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_mig_7series_0_1/PCIe_mig_7series_0_1/user_design/constraints/PCIe_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_dma_0_0/PCIe_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_dma_0_0/PCIe_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_fpga_relu_accelerator_0_0/constraints/fpga_relu_accelerator_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_0/PCIe_axi_interconnect_0_imp_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_0/PCIe_axi_interconnect_0_imp_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_0/PCIe_axi_interconnect_0_imp_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_1/PCIe_axi_interconnect_0_imp_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_1/PCIe_axi_interconnect_0_imp_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_1/PCIe_axi_interconnect_0_imp_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_2/PCIe_axi_interconnect_0_imp_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_2/PCIe_axi_interconnect_0_imp_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_us_2/PCIe_axi_interconnect_0_imp_auto_us_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_cc_0/PCIe_axi_interconnect_0_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_cc_0/PCIe_axi_interconnect_0_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_cc_0/PCIe_axi_interconnect_0_imp_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_ds_0/PCIe_axi_interconnect_0_imp_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_ds_0/PCIe_axi_interconnect_0_imp_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_ds_0/PCIe_axi_interconnect_0_imp_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_pc_0/PCIe_axi_interconnect_0_imp_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_ds_1/PCIe_axi_interconnect_0_imp_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_ds_1/PCIe_axi_interconnect_0_imp_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_ds_1/PCIe_axi_interconnect_0_imp_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/ip/PCIe_axi_interconnect_0_imp_auto_pc_1/PCIe_axi_interconnect_0_imp_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.gen/sources_1/bd/PCIe/PCIe_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.srcs/constrs_1/new/PCIe.xdc
set_property used_in_implementation false [get_files /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.srcs/constrs_1/new/PCIe.xdc]

read_xdc /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.srcs/constrs_1/new/debug_leds.xdc
set_property used_in_implementation false [get_files /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.srcs/constrs_1/new/debug_leds.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/wroomhers/Desktop/bitirme/pcie_xdma_ddr_ai_accel_test/pcie_xdma_ddr_ai_accel_test.srcs/utils_1/imports/synth_1/PCIe_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top PCIe_wrapper -part xc7a35tfgg484-2 -directive AreaOptimized_high -control_set_opt_threshold 1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef PCIe_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file PCIe_wrapper_utilization_synth.rpt -pb PCIe_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
